import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { navbarItems } from "@/lib/constants";
import { ThemeProvider } from "@/contexts/theme-context";
import { QueryProvider } from "@/contexts/query-provider";
import { PriceProvider } from "@/contexts/price-context";
import { ScaleWrapper } from "@/components/ui/scale-wrapper";
import { AppToaster } from "@/components/ui/app-toaster";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  variable: "--font-plus-jakarta-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable} antialiased`}
        style={{ fontFamily: 'var(--font-plus-jakarta-sans)' }}
      >
        <ThemeProvider>
          <QueryProvider>
            <PriceProvider>
              <Navbar items={navbarItems}/>
              <ScaleWrapper>{children}</ScaleWrapper>
              <AppToaster />
            </PriceProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
